---
- name: "build container with ansible"
  hosts: localhost
  tasks:
  - name: stop running cv-container
    command: docker stop httpd-foreground
    ignore_errors: yes

  - name: remove cv-container
    command: docker rm httpd-foreground
    ignore_errors: yes

  - name: remove cv-img
    command: docker rmi ahmedabdoahmed/cv-website:1.3
    ignore_errors: yes
    
  - name: pull image from dockerhub
    command: docker pull ahmedabdoahmed/cv-website:1.3

  - name: build docker image from dockerfile
    command: docker build -t ahmedabdoahmed/cv-website:1.3 .



  - name: run container from cv-img
    command: docker run -d --name cv-container -p 8082:80 cv-img 
