---
- name: "build container with ansible"
  hosts: localhost
  tasks:
  - name: stop running cv-container
    command: docker stop cv-container
    ignore_errors: yes

  - name: remove cv-container
    command: docker rm cv-container
    ignore_errors: yes

  - name: remove cv-img
    command: docker rmi cv-img
    ignore_errors: yes

  - name: build docker image from dockerfile
    command: docker build -t cv-img .
    ignore_errors: yes


  - name: run container from cv-img
    command: docker run  -p 8080:80 -d  ahmedabdoahmed/cv-website:1.3
